name: Sync Diagrams to Confluence

on:
  push:
    branches:
      - main
    paths:
      - 'docs/diagrams/**.mmd'
  workflow_dispatch:

jobs:
  sync_to_confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Confluence
        env:
          CONF_URL: ${{ secrets.CONFLUENCE_URL }}
          USERNAME: ${{ secrets.ATLASSIAN_USERNAME }}
          API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        run: |
          PAGE_TITLE="02-04-container"
          SPACE_KEY="EFM"
          BODY_CONTENT=$(cat docs/diagrams/02-04-container.mmd | sed 's/"/\\"/g')
          
          curl -u "$USERNAME:$API_TOKEN" \
            -X POST "$CONF_URL/rest/api/content" \
            -H "Content-Type: application/json" \
            -d "{
              \"type\":\"page\",
              \"title\":\"$PAGE_TITLE\",
              \"space\":{\"key\":\"$SPACE_KEY\"},
              \"body\":{\"storage\":{\"value\":\"<pre>$BODY_CONTENT</pre>\",\"representation\":\"storage\"}}
            }"
